### ISSUE TITLE
panic in `flowctl catalog pull-specs --overwrite`

### ISSUE THREAD

**Issue by psFried** [estuary/flow#1474]
Steps to reproduce:

- `flowctl catalog pull-specs --prefix foo/`
- `flowctl catalog pull-specs --prefix foo/ --overwrite` 💥 

Error output:

```
RUST_BACKTRACE=1 flowctl catalog pull-specs --prefix foo/ --overwrite
Wrote 43 specifications under file:///Users/phil/projects/wtf/flow.yaml.
thread 'tokio-runtime-worker' panicked at crates/sources/src/inline.rs:337:17:
assertion `left == right` failed: expected exactly one import from config scope file:///Users/phil/projects/wtf/foo/bar/flow.yaml#/captures/foo~1bar~1source-bing-ads/endpoint/connector/config
  left: 2
 right: 1
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
   4: sources::inline::inline_config
   5: sources::inline::inline_capture
   6: sources::inline::inline_sources
   7: build::validate::{{closure}}
   8: flowctl::local_specs::validate::{{closure}}
   9: flowctl::local_specs::generate_files::{{closure}}
  10: flowctl::catalog::Catalog::run::{{closure}}
  11: flowctl::Cli::run::{{closure}}
  12: flowctl::main::{{closure}}
  13: tokio::runtime::task::core::Core<T,S>::poll
  14: tokio::runtime::task::harness::Harness<T,S>::poll
  15: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  16: tokio::runtime::scheduler::multi_thread::worker::Context::run
  17: tokio::runtime::context::runtime::enter_runtime
  18: tokio::runtime::scheduler::multi_thread::worker::run
  19: tokio::runtime::task::core::Core<T,S>::poll
  20: tokio::runtime::task::harness::Harness<T,S>::poll
  21: tokio::runtime::blocking::pool::Inner::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at crates/flowctl/src/main.rs:29:12:
called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(3), ...)
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: flowctl::main
```

**Comment by jgraettinger** [comment]
Done
