### ISSUE TITLE
runtime: leaking goroutines as capture terms restart

### ISSUE THREAD

**Issue by jgraettinger** [estuary/flow#350]
I'm seeing 856 goroutines with the following stack:
```
goroutine 744958747 [select, 3 minutes]:
go.gazette.dev/core/keyspace.(*KeySpace).WaitForRevision(0xc000292270, {0x2836c88, 0xc03c84d500}, 0x1e20b)
	/home/runner/go/pkg/mod/github.com/estuary/gazette@v0.88.1-0.20220106163313-057c2852e3c9/keyspace/key_space.go:244 +0xe8
github.com/estuary/flow/go/runtime.signalOnSpecUpdate(0xc000292270, {0x284a040, 0xc0109dfa20}, 0xc10271b9e0, 0xc017e53480)
	/home/runner/work/flow/flow/go/runtime/task_term.go:184 +0x19b
created by github.com/estuary/flow/go/runtime.(*Capture).RestoreCheckpoint
	/home/runner/work/flow/flow/go/runtime/capture.go:124 +0x4b1
```

**Comment by jgraettinger** [comment]
Another common goroutine trace: 
```
goroutine 77286573 [chan receive, 21714 minutes]:
github.com/estuary/protocols/capture.(*adapterStreamServer).Recv(0xc006e56f48)
	/home/runner/go/pkg/mod/github.com/estuary/protocols@v0.0.0-20211213235942-5170046767ab/capture/adapter.go:209 +0x31
github.com/estuary/flow/go/capture/driver/airbyte.driver.Pull.func1({0xc002364f01, 0x2822e38})
	/home/runner/work/flow/flow/go/capture/driver/airbyte/driver.go:422 +0x43
github.com/estuary/flow/go/connector.runCommand.func1()
	/home/runner/work/flow/flow/go/connector/run.go:188 +0x8f
created by github.com/estuary/flow/go/connector.runCommand
	/home/runner/work/flow/flow/go/connector/run.go:186 +0x28f
```

We're failing to CloseSend of the in-process capture PullClient stream adapter, and that's wedging this goroutine even though we will never again send to the stream. Need to defer a CloseSend in `PullClient.Serve`.

**Comment by jgraettinger** [comment]
Similarly, within `capture.RestoreCheckpoint` we currently error if `Close` of the wrapped delegate returns an error.

This isn't quite what we want, because a) we've already logged the error when it was originally encountered, and b) a failure of the _previous_ processing term shouldn't fail _this_ one. At the moment we're seeing a behavior where every _other_ polling interval actually runs the connector, with others bailing out due to this error on cleanup.
