### ISSUE TITLE
Better Error Message for Invalid Credentials

### ISSUE THREAD

**Issue by dyaffe** [estuary/flow#486]
Problem:
If you use the wrong credentials for a google sheets connector, you get an error message that's not very helpful.  It would be nice to have better feedback in a case like this.

Steps to reproduce:
1.  Create a capture for Google Sheets using the Google analytics auth string from [this doc](https://docs.google.com/spreadsheets/d/1rGRtvx0_khLHTRckePvH5K7bzaV3Rdv4V2wPuJKpANI/edit#gid=0)
2. Save and publish
3. Get the error below.  

Error Message:
```
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 13, in <module>
    launch(source, sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 129, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 114, in run
    catalog = self.source.discover(self.logger, config)
  File "/airbyte/integration_code/google_sheets_source/google_sheets_source.py", line 96, in discover
    client = GoogleSheetsClient(self.get_credentials(config))
  File "/airbyte/integration_code/google_sheets_source/client.py", line 21, in __init__
    self.client = Helpers.get_authenticated_sheets_client(credentials, scopes)
  File "/airbyte/integration_code/google_sheets_source/helpers.py", line 28, in get_authenticated_sheets_client
    creds = Helpers.get_authenticated_google_credentials(credentials, scopes)
  File "/airbyte/integration_code/google_sheets_source/helpers.py", line 40, in get_authenticated_google_credentials
    return service_account.Credentials.from_service_account_info(json.loads(credentials["service_account_info"]), scopes=scopes)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 155 (char 154)"
time="2022-05-19T16:58:45Z" level=error msg="connector failed. command_config: CommandConfig { entrypoint: "python", args: ["/airbyte/integration_code/main.py", "discover", "--config", "/var/tmp/airbyte-source-wglOrW/config.json"] }."
time="2022-05-19T16:58:45Z" level=error msg="connector proxy execution failed."
time="2022-05-19T16:58:45Z" level=error msg="connector proxy execution failed."
time="2022-05-19T16:58:45Z" level=error msg="running connector failed" error="exit status 1" logSource="ghcr.io/estuary/airbyte-source-google-sheets:dev" operation=discover
time="2022-05-19T16:58:45Z" level=fatal msg="fatal error" err="exit status 1 with stderr:

{"timestamp":"2022-05-19T16:58:43.920940709Z","level":"WARN","message":"No connector protocol is specified in the image, using default: Airbyte"}
{"timestamp":"2022-05-19T16:58:45.165499807Z","level":"ERROR","message":"Unterminated string starting at: line 1 column 155 (char 154)\
Traceback (most recent call last):\
  File \\"/airbyte/integration_code/main.py\\", line 13, in <module>\
    launch(source, sys.argv[1:])\
  File \\"/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py\\", line 129, in launch\
    for message in source_entrypoint.run(parsed_args):\
  File \\"/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py\\", line 114, in run\
    catalog = self.source.discover(self.logger, config)\
  File \\"/airbyte/integration_code/google_sheets_source/google_sheets_source.py\\", line 96, in discover\
    client = GoogleSheetsClient(self.get_credentials(config))\
  File \\"/airbyte/integration_code/google_sheets_source/client.py\\", line 21, in __init__\
    self.client = Helpers.get_authenticated_sheets_client(credentials, scopes)\
  File \\"/airbyte/integration_code/google_sheets_source/helpers.py\\", line 28, in get_authenticated_sheets_client\
    creds = Helpers.get_authenticated_google_credentials(credentials, scopes)\
  File \\"/airbyte/integration_code/google_sheets_source/helpers.py\\", line 40, in get_authenticated_google_credentials\
    return service_account.Credentials.from_service_account_info(json.loads(credentials[\\"service_account_info\\"]), scopes=scopes)\
  File \\"/usr/local/lib/python3.9/json/__init__.py\\", line 346, in loads\
    return _default_decoder.decode(s)\
  File \\"/usr/local/lib/python3.9/json/decoder.py\\", line 337, in decode\
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\
  File \\"/usr/local/lib/python3.9/json/decoder.py\\", line 353, in raw_decode\
    obj, end = self.scan_once(s, idx)\
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 155 (char 154)"}
{"timestamp":"2022-05-19T16:58:45.238596897Z","level":"ERROR","message":"connector failed. command_config: CommandConfig { entrypoint: \\"python\\", args: [\\"/airbyte/integration_code/main.py\\", \\"discover\\", \\"--config\\", \\"/var/tmp/airbyte-source-wglOrW/config.json\\"] }."}
{"timestamp":"2022-05-19T16:58:45.238643799Z","level":"ERROR","error":"CommandExecutionError(\\"delayed process failed with code 1.\\")","message":"connector proxy execution failed."}
{"timestamp":"2022-05-19T16:58:45.239559794Z","level":"ERROR","error":"IOError(Custom { kind: Other, error: \\"Could not find message in stream\\" })","message":"connector proxy execution failed."}
"
```

**Comment by mdibaiee** [comment]
Fixed, the new logs are:
```
{"timestamp":"2022-06-01T17:32:16.700144435Z","level":"ERROR","message":"Failed to parse Service Account JSON credentials, please make sure the input is valid JSON."}
{"timestamp":"2022-06-01T17:32:16.701305359Z","level":"ERROR","message":"Expecting value: line 1 column 1 (char 0)\
Traceback (most recent call last):\
  File \\"/airbyte/integration_code/main.py\\", line 13, in <module>\
    launch(source, sys.argv[1:])\
  File \\"/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py\\", line 129, in launch\
    for message in source_entrypoint.run(parsed_args):\
  File \\"/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py\\", line 114, in run\
    catalog = self.source.discover(self.logger, config)\
  File \\"/airbyte/integration_code/google_sheets_source/google_sheets_source.py\\", line 96, in discover\
    client = GoogleSheetsClient(self.get_credentials(config))\
  File \\"/airbyte/integration_code/google_sheets_source/client.py\\", line 21, in __init__\
    self.client = Helpers.get_authenticated_sheets_client(credentials, scopes)\
  File \\"/airbyte/integration_code/google_sheets_source/helpers.py\\", line 28, in get_authenticated_sheets_client\
    creds = Helpers.get_authenticated_google_credentials(credentials, scopes)\
  File \\"/airbyte/integration_code/google_sheets_source/helpers.py\\", line 41, in get_authenticated_google_credentials\
    service_account_json = json.loads(credentials[\\"service_account_info\\"])\
  File \\"/usr/local/lib/python3.9/json/__init__.py\\", line 346, in loads\
    return _default_decoder.decode(s)\
  File \\"/usr/local/lib/python3.9/json/decoder.py\\", line 337, in decode\
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\
  File \\"/usr/local/lib/python3.9/json/decoder.py\\", line 355, in raw_decode\
    raise JSONDecodeError(\\"Expecting value\\", s, err.value) from None\
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)"}
```

Notice the first line is a more clear message about the JSON being invalid.
