### ISSUE TITLE
Error when disabling a capture

### ISSUE THREAD

**Issue by psFried** [estuary/flow#567]
I disabled a capture on a local instance, and managed to trigger a segfault that seems to have taken down the entire reactor process. Here's the logs from `temp-data-plane`:

```
INFO[23780] solved for maximum assignment                 assignments=2 desired=1 dur="12.715µs" hash=13251263143352958840 items=2 lastHash=345577745442414615 members=1 rev=57 root="/gazette/consumers/*runtime.FlowConsumer"
INFO[23781] initialized catalog task term                 labels="{06925d4ef3012c00 info key:00000000-ffffffff;r-clock:00000000-ffffffff   aliceCo/test3/source-gcs capture}" lastLabels="{06924fbde0811000 info key:00000000-ffffffff;r-clock:00000000-ffffffff   aliceCo/test3/source-gcs capture}"
INFO[23781] stopping local shard                          id=capture/aliceCo/test3/source-gcs/00000000-00000000
ERRO[23781] failed to initialize processing term          error="opening pull RPC: reading Opened: decrypting `sops` document: context canceled: "
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe003a2]

goroutine 1442 [running]:
github.com/estuary/flow/go/protocols/capture.(*PullClient).Close(0x0)
        <autogenerated>:1 +0x22
github.com/estuary/flow/go/runtime.(*Capture).Destroy(0xc0003aa580)
        /home/phil/projects/flow/go/runtime/capture.go:436 +0x2e
go.gazette.dev/core/consumer.waitAndTearDown(0xc0004d71e0, 0xc000258650)
        /home/phil/go/pkg/mod/go.gazette.dev/core@v0.89.1-0.20220422210424-fa37e21e0464/consumer/shard.go:306 +0x44
created by go.gazette.dev/core/consumer.(*Resolver).cancelShards
        /home/phil/go/pkg/mod/go.gazette.dev/core@v0.89.1-0.20220422210424-fa37e21e0464/consumer/resolver.go:394 +0x71
```

Note the timestamps of the logs, which seem to indicate that `Destroy` was called while the term was still initializing. At first glance, it seems that `Destroy` is not maintaining the documented invariants when calling [`Close`](https://github.com/estuary/flow/blob/39f3cb1eea89a721475c56f44cc8b4a251414cbf/go/protocols/capture/coordinator.go#L91), which states:

> The primary loop must have already initiated a close (due to an error, or context cancellation, or EOF).

**Comment by jgraettinger** [comment]
Yep! I hit this too, and believe I have[ it fixed via this commit ](https://github.com/estuary/flow/pull/565/commits/f16d884579957cbf9255a8505227c46fb74a99d0)on my current PR

**Comment by jgraettinger** [comment]
The specific issue is that `Destroy` calls `Close` if `c.delegate != nil`. However as per your stack trace, `PullClient.Close` is called with a nil self.

What's actually happening is that `c.delegate` is an interface, and a typed `(*PullClient)(nil)` interface value is _a distinct thing_ from `nil`. This is one of Go's more insane corners...
