### ISSUE TITLE
User Issue when Materializing to Postgres

### ISSUE THREAD

**Issue by dyaffe** [estuary/flow#661]
**Problem**
I'm not sure if this is a connector or runtime issue, but a user is seeing an segfault error on this materialization: `trial/colinb/Lightsail`

Here's the error:

```
completeRecovery: store.RestoreCheckpoint: opening transactions RPC: reading Opened: exit status 1 with stderr:

time="2022-09-08T13:40:03Z" level=info msg="opening database" address="ls-6fcd71c9134432c8eb1b1ea2dc4f6e2c9f142537.ctjs9atn553o.us-east-2.rds.amazonaws.com:5432" database=Estuary user=dbestuarytest
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xb3250a]

goroutine 1 [running]:
main.buildSQL(0xc000130e58, 0xc00015c000, 0xc0000cacc0, {{0xc000132240, 0x2, 0x2}, {0xc000444100, 0x9, 0x10}, {0x0, ...}, ...})
	/builder/materialize-postgres/driver.go:475 +0x48a
main.(*transactor).addBinding(0xc0003904b0, {0xdaeec8, 0xc00003aa00}, 0xc0003c0000)
	/builder/materialize-postgres/driver.go:202 +0x155
main.newPostgresDriver.func3({0xdaeec8, 0xc00003aa00}, {0xdb36a8, 0xc000130e40}, 0xc0003bc280, {0xda2d98, 0xc000390460}, {0xc0002abba0, 0x1, 0x1})
	/builder/materialize-postgres/driver.go:126 +0x2f4
github.com/estuary/flow/go/protocols/materialize/sql.(*Driver).Transactions(0xc0000942d0, {0xdb9e48, 0xc0003b8180})
	/go/pkg/mod/github.com/estuary/flow@v0.1.1-0.20220817221148-d68d91a3b3c1/go/protocols/materialize/sql/driver.go:334 +0x663
github.com/estuary/connectors/materialize-boilerplate.transactionsCmd.Execute(...)
	/builder/materialize-boilerplate/boilerplate.go:191
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc0000930a0, {0xc000132010, 0xc, 0x1})
	/go/pkg/mod/github.com/jessevdk/go-flags@v1.5.0/parser.go:335 +0x94e
github.com/jessevdk/go-flags.(*Parser).Parse(...)
	/go/pkg/mod/github.com/jessevdk/go-flags@v1.5.0/parser.go:191
github.com/estuary/connectors/materialize-boilerplate.RunMain({0xdb3038, 0xc0000942d0})
	/builder/materialize-boilerplate/boilerplate.go:45 +0x6c5
main.main()
	/builder/materialize-postgres/driver.go:488 +0x1e
```

**Comment by psFried** [comment]
This appears to another case of #653, so I'll close this one in favor of the original issue.
