### ISSUE TITLE
Connector containers are getting leaked

### ISSUE THREAD

**Issue by psFried** [estuary/flow#725]
Reactors seem to be leaking connector containers again. I observed one reactor pod that had 65(!) `materialize-snowflake` containers, despite only having a single snowflake materialization shard assigned. I've attached the goroutine traces from that reactor.

[goroutine-traces.txt](https://github.com/estuary/flow/files/9815259/goroutine-traces.txt)

**Comment by dhammika** [comment]
In my local setup stuck connectors were waiting on this accept(), 
https://github.com/estuary/connectors/blob/9b72f6cd1633b8de7c0a04697617feef558efe14/materialize-boilerplate/boilerplate.go#L38-L41 
Shutdown SIGTERM signals are actually delivered but the signal notify context is effectively in mute. It's also holding listen socket for the full duration of the cmd. But upserts, transactions etc. can be long lived processes.

**Comment by mdibaiee** [comment]
@dhammika this is a good find. First off, if the connectors are stuck on this step it means the runtime didn't connect to them properly. But in any case, we should probably have a timeout on the connector's side as well so that we don't wait forever for the runtime to connect and if the runtime fails to connect for any reason (e.g. a bug in the runtime or any other valid reason), we just exit with an error in the connector.

**Comment by mdibaiee** [comment]
@dhammika does this make sense? https://github.com/estuary/connectors/pull/391

**Comment by dhammika** [comment]
In my local setup I see stuck connectors waiting on a transaction, 
```
time=\"2022-10-24T03:37:01Z\" level=info msg=\"opening database\" address=\"postgres:5432\" database=flow user=flow
time=\"2022-10-24T03:37:01Z\" level=info msg=\"starting network-tunnel\" forward-host=postgres forward-port=5432 local-port=5432 ssh-endpoint=\"ssh://flowssh@openssh-server:2222\"
time=\"2022-10-24T03:37:01Z\" level=info msg=\"network-tunnel ready\"
{\"timestamp\":\"2022-10-24T03:37:31.407872812Z\",\"level\":\"ERROR\",\"exit_code\":\"Some(255)\",\"message\":\"network tunnel ssh exit with non-zero code.\"}
{\"timestamp\":\"2022-10-24T03:37:31.408130013Z\",\"level\":\"ERROR\",\"message\":\"network tunnel failed.\",\"error\":\"TunnelExitNonZero(\\"ExitStatus(\\n    unix_wait_status(\\n        65280,\\n    ),\\n)\\")\"}
SIGABRT: abort
PC=0x49ece1 m=0 sigcode=0

goroutine 0 [idle]:
runtime.futex()
	/usr/local/go/src/runtime/sys_linux_amd64.s:519 +0x21
runtime.futexsleep(0x7ffd42750840, 0x4788f3, 0xc000043000)
	/usr/local/go/src/runtime/os_linux.go:44 +0x36
runtime.notesleep(0x1891f50)
	/usr/local/go/src/runtime/lock_futex.go:160 +0x87
runtime.mPark()
	/usr/local/go/src/runtime/proc.go:1441 +0x2a
runtime.stoplockedm()
	/usr/local/go/src/runtime/proc.go:2602 +0x65
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:3299 +0x3d
runtime.park_m(0xc0000a3ba0)
	/usr/local/go/src/runtime/proc.go:3516 +0x14d
runtime.mcall()
	/usr/local/go/src/runtime/asm_amd64.s:307 +0x43

goroutine 1 [select, 12 minutes]:
github.com/estuary/flow/go/protocols/materialize.RunTransactions({0x12a2748, 0xc000328180}, {0x129c530, 0xc000336800}, 0xc000258230)
	/go/pkg/mod/github.com/estuary/flow@v0.1.5-0.20221007131251-5f24d1137ec0/go/protocols/materialize/transactor.go:281 +0x1245
github.com/estuary/flow/go/protocols/materialize/sql.(*Driver).Transactions(0xc000081680, {0x12a2748, 0xc000328180})
	/go/pkg/mod/github.com/estuary/flow@v0.1.5-0.20221007131251-5f24d1137ec0/go/protocols/materialize/sql/driver.go:345 +0xecd
github.com/estuary/connectors/materialize-boilerplate.transactionsCmd.Execute(...)
	/builder/materialize-boilerplate/boilerplate.go:216
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc000258b60, {0xc000032090, 0xc, 0x3})
	/go/pkg/mod/github.com/jessevdk/go-flags@v1.5.0/parser.go:335 +0xf10
github.com/jessevdk/go-flags.(*Parser).Parse(...)
	/go/pkg/mod/github.com/jessevdk/go-flags@v1.5.0/parser.go:191
github.com/estuary/connectors/materialize-boilerplate.RunMain({0x129b8d8, 0xc000081680})
	/builder/materialize-boilerplate/boilerplate.go:70 +0xe0c
main.main()
	/builder/materialize-postgres/driver.go:533 +0x2a

goroutine 20 [syscall, 12 minutes]:
os/signal.signal_recv()
	/usr/local/go/src/runtime/sigqueue.go:169 +0x98
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:24 +0x25
created by os/signal.Notify.func1.1
	/usr/local/go/src/os/signal/signal.go:151 +0x53

goroutine 34 [select, 12 minutes]:
os/signal.NotifyContext.func1()
	/usr/local/go/src/os/signal/signal.go:288 +0xd1
created by os/signal.NotifyContext
	/usr/local/go/src/os/signal/signal.go:287 +0x2c5

goroutine 22 [select, 12 minutes]:
database/sql.(*DB).connectionOpener(0xc0001cc1a0, {0x1296b38, 0xc000032740})
	/usr/local/go/src/database/sql/sql.go:1196 +0xfa
created by database/sql.OpenDB
	/usr/local/go/src/database/sql/sql.go:794 +0x307

goroutine 69 [select, 12 minutes]:
os/exec.(*Cmd).Start.func2()
	/usr/local/go/src/os/exec/exec.go:452 +0xf1
created by os/exec.(*Cmd).Start
	/usr/local/go/src/os/exec/exec.go:451 +0xe14

goroutine 31 [IO wait, 12 minutes]:
internal/poll.runtime_pollWait(0x7f75ced9e720, 0x72)
	/usr/local/go/src/runtime/netpoll.go:303 +0x85
internal/poll.(*pollDesc).wait(0xc00016f098, 0xc000400000, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0xbd
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc00016f080, {0xc000400000, 0x200000, 0x200000})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x419
net.(*netFD).Read(0xc00016f080, {0xc000400000, 0x200000, 0x200000})
	/usr/local/go/src/net/fd_posix.go:56 +0x51
net.(*conn).Read(0xc000010a78, {0xc000400000, 0x200000, 0x200000})
	/usr/local/go/src/net/net.go:1" logSource="ghcr.io/estuary/materialize-postgres:local" operation=transactions
```
Connection is dropped here (note tunnel error) but I'm not sure how inflight transaction is unrolled,
https://github.com/estuary/flow/blob/f996ecd19d0bfefedbb7a3429499bc27ab6c36da/go/protocols/materialize/transactor.go#L279-L295
